# Generated by Django 5.1.3 on 2024-11-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnibkend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furnitures',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
