# Generated by Django 5.1.3 on 2025-02-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnibkend', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.TextField(default='No default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='position',
            field=models.CharField(default='Member', max_length=100),
        ),
    ]
