# Generated by Django 5.1.3 on 2025-02-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnibkend', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='chair',
        ),
    ]
